package main

import (
	"fmt"

	"github.com/bitlux/caches/util"
)

type Dir byte

const (
	North Dir = iota
	East
	South
	West
)

var message = []string{
	"PQUIKEDMBZVRKNEQMQFBGCXEQOINXBZYKRZSBVXRKYIKAJKPFZV",
	"EBXFTELPRXHZDELOAFYOMNAKFSAZMUUXBEMYIRXWXHKQTTMMZYH",
	"NASPFLVARCEAZAHUJOLGUUCEQYBKYMIPSGBGVAXSWLIGBLIYLSQ",
	"WXTXULXFQPNWVFXWDSFPVDSEPKODBBHVCVSUMUFXCBENAJKQQLI",
	"SXDGORARDLMEJUSNWIYTSGALQRAFAUAIIVBNCOUKNABXZSALVIU",
	"NRKPDHQVTTOMLECHWVVYTWXKGQVFJXSUPNOAPLJNIRVJNVPOTTG",
	"ZGAFPFCUYSRHHNMUTGUNDCMKIKUVXVQXHTBOZFAPDBFXNPLGAFO",
	"GVGHFLYRQVKYSOPLABKVPAJKEJDVTMYSFSMOYJEVAITUFCLCBJI",
	"DGWRMSYYUOJSLTLRRRGFVWZJTIAUZNGDERSHBTSHLOBNPNRIIKF",
	"FCTDBESROGCFGNNTCWLFTESIEQLOERHPXBXEUCHEPXCBXHZJRUU",
	"GQIFVWELLXXGSGABRYPGQAYSIJBDCYHQKWHXKOMUCXSGBUJZDTH",
	"GZZWIVAGQDNUJOFUBTIFHAQFJMNYVQODBYBKLKXJTNOBKLJLXPH",
	"XQZFMXVOZHSWUFJFYLATDORWVKSDQHLIWPADKZAANSKFTYQRJJH",
	"SRULNPSMKEWRJIIQXATOCPBXENARFYHOEHNCPOYYDYTIXHGXWOR",
	"LHBOKIGDHIOIIHYRTPOIKRDEYJVHOGIUUBNNJKSSHCBITPCNUHQ",
	"QDCAVJBILQNDFEXVNQINPGGELZWXNKTWIOVYTTSSQVZMHZNGUUQ",
	"YUNURWTLZFPOYGVUCSGWWBMCWEZYHFEHIPKTEXHVPJSMDGOHYBY",
	"UODXKGYUBRBEQOFOIWYWCGIWWIVSHPKFDXIOZWPFKWJKDKWDFQA",
	"NOHWLTJFPMLWVQWZPCVAXXXIMDGPBJGHIBGGFEULYPIQHPRHEWF",
	"CSYBJEPQVTYZWYFHQUAOVRYNOUNRWVAROZNKYLUHIUEQNUDVHYK",
	"FSGJDLHUJEXYKVMIXSVYSIKNTJXGDPFHTKBDDCKZCBODAOFFTGG",
	"ADBOFBTEFISNHYEQMDVXIWGIRANWALTDASJUNGRBPAEDYJGJBUI",
	"TXTOBLCITMNZCRDQNHZDTPIDAWVUOPDEQWUVEDGETUDDZXPXGYH",
	"GHNZFNIIUTHZUPPLXPVZGPSATEQXVSMPWJWPBPMQDHGJAHEPPNQ",
	"DBBTNZHHBBZZPHWKKPQUQTKDOHPRNCLUTBTBLJJFSFUINSTMMCJ",
	"XCKTBORYROWTETLJTXCDHCPZLRZJMBRWVFNQOGRASVDTJBQVZBP",
	"VZBBWPPWKXVJFDVAWZJLCIRRNNZMHWUZGBJPNLNMJMNDRVHZTUV",
	"NOLSFGXPKAVULXOLAICDPPVVKYLIWYDTSMUSYDVIEPTWFPMICZQ",
	"SGYKRCOIOTGCPYROYXKZOJRRQXXQNHNXYTLNYRQFCJBCRMRIAQY",
	"RDANOIFDNKUZSVFZUREIXSIUBVRNWCQENEXVGFNPTRBOKCYIYTQ",
	"OUHLWRDUDRRIQCHKHWNZOYYZLAERETENZJZWIVUSOQCWOTMGBTG",
	"TGPBVNCPHGUBFWRGDZBICBHPDALMVLHSORCNLHNYXJWGZRCLOKV",
	"PRBVJIPGAJRLAPHXNKWUTGUBBZOCMDNKZEJGAZXIXTSPAODVXXO",
	"XPOIOJSKOAURNKWBFOTXYGEZPFQJTIHLDUCHQXXOUHANICUUDXS",
	"SEFXLDOYZBNYTGDTPLNDBVGXKTWFYCDBRWPMUIUFOLPFNFYLXMP",
	"WPTQQEKFPSNELEUWMAUGBUMDIAXKVNFRONPVIVLMZFOZGIFXKTZ",
	"ZZAGHMGXIPXGWVIUTCJXBTTKOIJMBESEBVCREYHAQXVAZOCVZZO",
	"LPSYIULTXTJSWHMEUUOKKUWEPFFKDCIMFBHRWEZCYBEGDXTGZFU",
	"TFOFBPYVWMAUGEAFEBXRSUKTKMQDQIEKVRMDBGUETFTRDNPIJJB",
	"CIMOBNEXTASSLNDXYNZNAYDXNWLDZGWTTTSUQNZHOUTVYBYIJAB",
	"DDHWSRIZSJETBCKINPCTJDDSZMPXKUEJBUPLBASXJKMPQMJPZRF",
	"ECUBWBPBYZFTKGCEIJMFTTTVDXEZHLWMSAXTAPYBZSTNRIDYFMN",
	"YCDPUUIRDMMNXZOTYWRVPTMSATWHGADNEIQCTCWVMWJNRTEWJJJ",
	"NEAYYNZAYTDZMVYIRVBEZXHNENZJMSSONJTLYSHYYKSSSRSZFSQ",
	"CSFCWLEYRIANSMOTPSKYFSKOCXMAQIRYOGRRKDHXHSWBMCHWZKX",
	"ZDILVOOWQEWWVHKFADKVGQNIRCSPIVEQELINBBQMFUULHFTKUNP",
	"EZAYLVEZQRHWNUDEAOLWADJFWVOPLNOSCDJPKTPHXYSBBNWBXRE",
	"OWRIJYTZRUSPUUXIAGJVVYDXYNFYBGIFIGUGEAXKSNXBPCFKHOX",
	"GRADIULWBDRLKTXBLVRIGDWWNESYGVJOXWBKOBRTXLGFFJJCGOK",
	"NEJCUHBZACDZLFRROOTOGOYFKPUWENFARHPHOHNBRXJBVXWLDFH",
	"FCIVKGINMQFQPJOGKCZNRVQIDAFSDKSVWLNHBPYEUVXFLSOVLNJ",
}

var (
	height = len(message)
	width  = len(message[0])
)

type state struct {
	row, col int
	dir      Dir
	start    bool
}

func (s *state) next() {
	letter := message[s.row][s.col]
	fmt.Printf("%c", letter)

	number := util.A1Encode(letter)

	if s.start {
		s.start = false
	} else {
		if number < 10 {
			s.dir = (s.dir + 3) % 4
		}
		if number > 18 {
			s.dir = (s.dir + 1) % 4
		}
	}

	distance := ((number - 1) % 9) + 1

	switch s.dir {
	case North:
		s.row = (s.row - distance + height) % height
	case East:
		s.col = (s.col + distance) % width
	case South:
		s.row = (s.row + distance) % height
	case West:
		s.col = (s.col - distance + width) % width
	}
}

func main() {
	s := &state{row: height - 1, col: 34, dir: North}
	for range 200 {
		s.next()
	}
}
