package main

import "fmt"

const chars = `XNVWEEWTSWOFRNOHLNORTHXYWESTNTSTSMTOUSSVEOUTWBTCWSEWHSNCSHJSEOSWRNUMWOOEA
OWWWNSHETSWWJNXHONUTHTEWOWRHTNMONNEBHCWNQSRSHHHENSEWTETPTHSEEHHEKNZNTEWCB
SSTESOISETRNITEJHTEGEWSSNPWDHEHTOHWOTTOMOTERWFEREMSTSWTOJAMTUOWEWLGSTAOEC
ONSSOZOHONRWCIETTTWWWRTNOWNSHTNOOOSRDDWHOSEHTWEENSEJWEJOOSRTVWNNRZSTSWTFD
ESEVONVETWNSNOEOESRWWRRHTEWTHOHFWNWOHTHRTHWOTRWUFSHESONWETLEOWWSSSSNEHHEF
UWLTAOYWEWWHNNHEVQNWNNSSEWFSNNSBNDSEWDWHSENTWSYSQRSEWYHEROEWONESKDWNPERWG
WSWHWEYNRESEEOTRWSTTWSEVMSBEWWHTRRWPREXOOSJEHNIEREHOESHUYWWEEZEWRSSNSNESI
HETTRLYFEREEHTNSSYFCHESHEGUHSDSGNRENXRKWWNWRATJNNHWEMENESSETWTRUSHEWHEJNJ
ENYSHWTUERCRETSSOPEWENQOWHSRSSTOHETNHEMZEHBSTEUNTNOTEEWEWWQEHVSEZSRWWROTK
SSURJJEHROTRTEWRMROETWFTSWTWDVAREIHOHHZGWBGJMESENWHTWVSSCOWSTNEHDNENOJHGL`

func main() {
	for _, kw := range []string{"NORTH", "WEST"} {
		keyworth := map[rune]int{}
		i := 1
		for _, c := range kw {
			keyworth[c] = i
			i++
		}

		total := 0
		curr := 0
		for _, c := range chars {
			if w := keyworth[c]; w != 0 {
				curr = 10*curr + w
			} else {
				total += curr
				curr = 0
			}
		}
		fmt.Println(total)
	}
}
